# Generated by Django 6.0.4 on 2026-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_days', models.IntegerField(default=30)),
            ],
        ),
    ]
