# Generated by Django 6.0.5 on 2026-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_roi', models.FloatField()),
                ('duration_days', models.IntegerField()),
                ('hashrate', models.CharField(max_length=50)),
            ],
        ),
    ]
